name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resume
        uses: actions/checkout@v3
      - name: Check cached resume
        id: cache-resume
        uses: actions/cache@v3
        with:
          path: resume.pdf
          key: ${{ runner.os }}-${{ hashFiles('resume.tex') }}
      - name: Download the fonts
        if: steps.cache-resume.outputs.cache-hit != 'true'
        run: "wget http://www.exljbris.com/dl/fontin_pc.zip && unzip -d fonts fontin_pc.zip && mv fonts/Fontin{-Regular,}.otf"
      - name: Build resume
        if: steps.cache-resume.outputs.cache-hit != 'true'
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
          post_compile: "latexmk -c"
      
  # Build job
  build:
    runs-on: ubuntu-latest
    needs: resume
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get cached resume
        uses: actions/cache@v3
        with:
          path: resume.pdf
          key: ${{ runner.os }}-${{ hashFiles('resume.tex') }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.133.0
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl ""
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: https://bmalyn.com
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
